# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb9c3f36256ea712dc265f41b5878a7c43a79fecfdffb4370693f49a642e6f2e49fc8f86e5e8df65655741b48db1e0df990ab1fd95045953a3b0b98f5e427a9d

test:
  secret_key_base: 3d3ee7cdd986278778c607be841c4868fdeb6b719b36d2d657555db5e586ed5201a799e617cb07556c749324219e37ae62412cb8f8491cc0b179e3b03483cc60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: bb9d5c8fde486a1f536af8d96cc8d80462e0f604395f01e4110c539a227e3f52830aa8fafefcc4578d90c63097cb1ff310b397055ddf0b88f0401fdf74d1ab4f

